package io.github.bolzer.easybill_java_sdk.enums;

public enum PostSendType {
    POST_SEND_TYPE_STANDARD,
    POST_SEND_TYPE_REGISTERED,
    POST_SEND_TYPE_REGISTERED_AND_PERSONAL,
    POST_SEND_TYPE_REGISTERED_AND_RECEIPT,
    POST_SEND_TYPE_REGISTERED_THROWIN,
    POST_SEND_TYPE_PRIO,
}
